GET http://localhost:5000/mahesas

###
GET http://localhost:5000/mahesa/1


###
POST http://localhost:5000/mahesa
Content-Type: application/json

{
    "nama": "Kolam Makarios",
    "lokasi": "Koya-Tondano Selatan",
    "desk" : "Pemandian air panas"
}

###
PATCH http://localhost:5000/mahesa/1
Content-Type: application/json

{
    "nama": "Benteng Moraya",
    "lokasi": "Tuutu-Tondano Utara",
    "desk" : "Tempat wisata budaya yang berada di jantung minahasa"
}

###
DELETE http://localhost:5000/mahesa/6
